### ISSUE TITLE
IOS -  stuck at data loading page

### ISSUE THREAD

**Issue by kim841** [MaisonMONA/mona-mobile#114]
**Describe the bug**
As the title described

**To Reproduce**
For new install or already install app
1. run `ionic cap run ios -l --external `
2. can't go futher than data loading page

**Tried but won't work**
- in data loading page, change gif for text (don't fix it)

**Smartphone (please complete the following information):**
 - OS: IOS

**Comment by SarahHCode** [comment]
Just tested it and it works now! (Maybe it was because of the images bug that we corrected previously)
