### ISSUE TITLE
Account page layout 

### ISSUE THREAD

**Issue by kim841** [MaisonMONA/mona-mobile#120]
**To Reproduce**
1. Ionic cap build

**Expected behavior**
Should look like this
![image](https://github.com/user-attachments/assets/cfe7e0b5-874a-48ed-bdb8-9cfa5f4538e5)

**Screenshots**
![image](https://github.com/user-attachments/assets/3a53c0c2-9647-4c8e-a9b5-0caaa74166d8)

**Smartphone (please complete the following information):**
 - OS: Android && IOS

**Comment by SarahHCode** [comment]
Fixed by https://github.com/MaisonMONA/mona-mobile/pull/123
