### ISSUE TITLE
MAJ des données côtés serveur ne se retrouve pas dans l'app

### ISSUE THREAD

**Issue by kim841** [MaisonMONA/mona-mobile#51]
**Describe the bug**
Lorsque le serveur met à jour les données, cela ne se réflète pas dans l'app. Maintenant, seule la désinstallation et réinstallation permet de voir le nouveau contenu.

**Expected behavior**
À l'ouverture de l'application, il faudrait vérifier si les contenus des discoveries en cache correspondent avec ceux du serveur. Si non, overwrite et repopuler la map et données.

**Comment by lenaMK** [comment]
utiliser lastUpdated : https://github.com/MaisonMONA/mona-server/wiki/Artworks-API-Endpoints#get-apiv3lastupdatedartworks

**Comment by kim841** [comment]
Le problème se trouvait dans lasUpdated
