### ISSUE TITLE
Implémenter les badges

### ISSUE THREAD

**Issue by Biskweet** [MaisonMONA/mona-mobile#7]
Implémenter les badges. Idéalement, on télécharge aussi les icônes de badges automatiquement depuis le serveur par cohérence avec le reste.

**Comment by kim841** [comment]
Il reste à
- [ ] Notifier l'utilisateur lorsqu'il obtient un nouveau badge
- [ ] Cliquer sur un badge doit faire apparaitre une fiche détaillée de cet badge (comme la version IOS)
