### ISSUE TITLE
Images du tutoriel ne s'affichent pas

### ISSUE THREAD

**Issue by kim841** [MaisonMONA/mona-mobile#74]
**Describe the bug**
Les images du tutoriels ne s'affichent pas

**To Reproduce**
1. L'utilisateur installe l'app pour la première fois
2. L'app ouvre
3. Le tutoriel ne s'affiche pas
4. Le button pour faire défiler les images fonctionne

**Additional context**
Après avoir fait "ionic cap build android" et rouler l'app dans android studio, les images ne sont pas présents

**Comment by SarahHCode** [comment]
Déplacer folder images (drawable) dans folder public et refactor les alias(@) avec . pour que les images fonctionnent. (Débuggé avec Kim et Sarah)
